### ISSUE TITLE
textnodes are wrapped in span

### ISSUE THREAD

**Issue by ivanceras** [cramertj/domafic-rs#8] opened 2017-02-08 13:12 UTC
Is there a way to insert a text inside a `div` that is a valid html as well?

``` 
div ((
          "<svg> ... </svg>".into_node()
       ))
```

**Comment by cramertj** [comment] 2017-02-09 22:42
No, in fact, if you're working off of master then the string nodes are HTML-encoded when rendering to a string. I don't thing string nodes are the right path for this. Just out of curiosity, why do you need stringly-typed HTML? That's something I'd be interested in supporting if you can explain your usecase.

**Comment by ivanceras** [comment] 2017-02-09 23:48
This is equivalent to `node.innerHTML = "<html document>"`. 
I have a [library that convert ascii text to svg drawings](https://github.com/ivanceras/svgbobrus). I have to slap in the resulting svg into the page

**Comment by cramertj** [comment] 2017-02-10 00:15
It is equivalent to `innerHTML`, yes-- I wanted to avoid encouraging `innerHTML`-style patterns for a variety of reasons, not the least of which is that each page update would require re-rendering the HTML string. I would encourage you to implement `DOMNode` for your `SVG` type.

**Comment by cramertj** [comment] 2017-02-10 00:17
Ah, it looks like you're using the [svg crate](https://github.com/bodoni/svg). I'd accept a PR implementing `DOMNode` for their `SVG` type.

**Comment by cramertj** [comment] 2017-02-14 00:39
I'm closing this as expected behavior. Feel free to comment if you don't agree.

**Closed as completed by cramertj** 2017-02-14 00:39 UTC
